config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  get 'admin/index'
  
  get 'admin' => 'tickets#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  get 'users' => 'users#index'
  

  resources :users

  root 'tickets#new'

end

app/models/ticket.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class Ticket < ActiveRecord::Base
  belongs_to :user
  
  validates :first_name, :last_name, :job_title, :department,
            :date_needed_by, :email, :priority, :position, :type_of_request, :purpose,
            :description, :time_period, :student_type, :campus,
            presence: true
  
  validates :email, presence: true, email: true
  validates :phone_number, presence: true, numericality: true
  
  validates_each :date_needed_by do |record, attr, value|
    record.errors.add(attr, 'must be not in the past') if value <= Time.now.to_date
  end
  
end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end
class User < ActiveRecord::Base
  has_many :tickets
  
  validates :name, presence: true, uniqueness: true
  has_secure_password
  
  after_destroy :ensure_an_admin_remains
  
  validates :email, presence: true, email: true
  
  private
    def ensure_an_admin_remains
      if User.count.zero?
        raise "Can't delete last user"
      end
    end
  
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_users = User.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  protected
    def authorize
      unless User.find_by(id: session[:user_id]) and User.find_by(id: session[:user_id])[:admin]
        redirect_to login_url, notice: "Please, log in."
      end
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize
    
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user and user.authenticate(params[:password]) and user.admin
      session[:user_id] = user.id
      redirect_to admin_url
    elsif user and user.authenticate(params[:password])
      redirect_to login_url, alert: "Programmers can't log in!"
    else
      redirect_to login_url, alert: "Invalid user/password combination"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_url, notice: "Logged out" #need to update it to the actuall link to creating the ticket
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :new]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket[:user_id]
      @ticket[:status] = 'Assigned'
    else
      @ticket[:status] = 'To be Assigned'
    end
    

    respond_to do |format|
      if @ticket.save
        if session[:user_id]
          format.html { redirect_to tickets_url, notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        else
          format.html { redirect_to new_ticket_url, notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        end
        if @ticket[:user_id]
          TicketNotifier.assigned(@ticket).deliver
        end
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
    if @ticket[:status] == 'Completed'
    elsif @ticket[:user_id]
      @ticket[:status] = 'Assigned'
    else
      @ticket[:status] = 'To be Assigned'
    end
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
        if @ticket[:user_id]
          if  @ticket[:status] != 'Completed'
            TicketNotifier.assigned(@ticket).deliver
          end
        end
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:first_name, :last_name, :job_title, :department,
                                     :phone_number, :date_needed_by, :email, :priority,
                                     :position, :type_of_request, :purpose, :description,
                                     :time_period, :student_type, :campus, :user_id,
                                     :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue StandardError => e
      flash[:notice] = e.message
    end
      respond_to do |format|
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email, :admin)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<div class="row">
  <div class="col">
    It's <%= Time.now %>
    <p>
      There will be the list of all of the tickets (Like Ticket.count, than @tickets.each do |ticket|)
    </p>
    <p>
      But we still can put here users count: <%= pluralize(@total_users, "user") %>.
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketing system</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= controller.controller_name %>'>
    <div id="main-container" class="container">
      <div class="row">
	<div class="col-sm-1">
          <div class="row">
            <h2>Menu</h2>
          </div>
          <ul class="list-unstyled">
	    <li><p><%= link_to "New ticket", new_ticket_path %></p></li>
	    <% if session[:user_id] %>
	      <li><p><%= link_to "Users", users_path %></p></li>
	      <li><p><%= link_to "Tickets", tickets_path %></p></li>
	      <li><p><%= link_to "Logout", logout_path, method: :delete %></p></li>
	    <% else %>
	      <li><p><%= link_to "Login", login_path %></p></li>
	    <% end %>
            <!--<li><a href='https://www.facebook.com/sharer/sharer.php?u=URL'>Share on Facebook</a></li>-->
          </ul>
	</div>
	<div class="col-sm-11">
	  <%= yield %>
	</div>
      </div>
    </div>
  </body>
</html>

app/views/ticket_notifier/assigned.html.erb
<h1>New ticket assigned to you!</h1>

<p>
  Hey, <%= User.find_by(id: @ticket.user_id)[:name] %>!
</p>

<p>There is one ticket for you!</p>

<p>Here is details:</p>

<%= render @ticket -%>

app/views/ticket_notifier/assigned.text.erb
Hey, <%= User.find_by(id: @ticket.user_id)[:name] %>!

There is one ticket for you!

Here is details:

<%= render @ticket -%>

app/views/ticket_notifier/solved.html.erb
<h1>TicketNotifier#solved</h1>

<p>
  <%= @greeting %>, find me in app/views/ticket_notifier/solved.html.erb
</p>

app/views/ticket_notifier/solved.text.erb
TicketNotifier#solved

<%= @greeting %>, find me in app/views/ticket_notifier/solved.text.erb

app/views/tickets/_form.html.erb
<%= form_for(@ticket, html: {class: 'form-horizontal'}) do |f| %>
  <% if @ticket.errors.any? %>
    <div class="row">
      <div class="input-group col-sm-7 col-md-offset-2">
        <div id="" class="form-group bg-warning">
          <ul>
            <dt><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</dt>
            <% @ticket.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  
  <% if session[:user_id] %>
    <div class="form-group">
      <%= f.label  :user_id, 'Assign to', class: 'col-sm-2 control-label' %>
      <div class="input-group col-sm-7">
        <%= f.collection_select :user_id, User.all, :id, :name, :include_blank => true, class: 'form-control' %>
      </div>
    </div>
    <!--<div class="form-group">-->
    <!--  <%= f.label  :status, class: 'col-sm-2 control-label' %>-->
    <!--  <div class="input-group col-sm-7">-->
    <!--    <%= f.select :status, ['Assigned', 'To be Assigned', 'Completed'], class: 'form-control' %>-->
    <!--  </div>-->
    <!--</div>-->
  <% end %>
  <div class="field form-group">
    <%= f.label :first_name, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :first_name, class: 'form-control', placeholder: 'Your name' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :job_title, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :job_title, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :department, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :department, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone_number, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :phone_number, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_needed_by, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.date_select :date_needed_by %>
      <!--<label for="ticket_date_needed_by" class="input-group-addon glyphicon glyphicon-calendar"></label>-->
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :email, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :priority, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.select :priority, ['1 - High', '2 - Standart', '3 - Low', '4 - Special'], :include_blank => true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.select :position, ['Faculty', 'Staff', 'Student', 'Other'], :include_blank => true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type_of_request, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.select :type_of_request, ['Internal', 'External', 'Other'], :include_blank => true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :purpose, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :purpose, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_area :description, class: 'form-control', rows: 5 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :time_period, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.text_field :time_period, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :student_type, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.select :student_type, ['All student', 'Undergraduate', 'Freshman', 'Full-time'], :include_blank => true, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :campus, class: 'col-sm-2 control-label' %>
    <div class="input-group col-sm-7">
      <%= f.select :campus, ['1. Main Campus', '2. Gallop', '3. Taos', '4. Valencia'], :include_blank => true, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2"></div>
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tickets/_ticket.html.erb
<dl>
  <dt>First name:</dt>
  <dd><%= @ticket.first_name %></dd>
  
  <dt>Last name:</dt>
  <dd><%= @ticket.last_name %></dd>

  <dt>Job title:</dt>
  <dd><%= @ticket.job_title %></dd>

  <dt>Department:</dt>
  <dd><%= @ticket.department %></dd>

  <dt>Phone number:</dt>
  <dd><%= @ticket.phone_number %></dd>

  <dt>Date needed by:</dt>
  <dd><%= @ticket.date_needed_by %></dd>

  <dt>Email:</dt>
  <dd><%= mail_to(@ticket.email) %></dd>

  <dt>Priority:</dt>
  <dd><%= @ticket.priority %></dd>

  <dt>Position:</dt>
  <dd><%= @ticket.position %></dd>

  <dt>Type of request:</dt>
  <dd><%= @ticket.type_of_request %></dd>

  <dt>Purpose:</dt>
  <dd><%= @ticket.purpose %></dd>

  <dt>Description:</dt>
  <dd><%= @ticket.description %></dd>

  <dt>Time period:</dt>
  <dd><%= @ticket.time_period %></dd>

  <dt>Student type:</dt>
  <dd><%= @ticket.student_type %></dd>

  <dt>Campus:</dt>
  <dd><%= @ticket.campus %></dd>
  
  <dt>Responsible</dt>
  <% if User.find_by(id: @ticket[:user_id]) %>
    <dd><%= User.find_by(id: @ticket[:user_id])[:name] %></dd>
  <% else %>
    <dd>Nobody is responsible</dd>
  <% end %>
  <dt>Status</dt>
  <dd><%= @ticket[:status] %>
</dl>

app/views/tickets/_ticket.text.erb
<%= sprintf("%s + %s", ticket.purpose, ticket.description) %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All of our tickets</h1>

<table class="table table-hover">
  <caption>Tickets count: <%= @tickets.count %></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Purpose</th>
      <th>Date needed by</th>
      <th>Priority</th>
      <th>Type of request</th>
      <th>Campus</th>
      <th>Responsible</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.first_name + " " + ticket.last_name %></td>
        <td><%= ticket.job_title + " from " + ticket.department %></td>
        <td><%= ticket.purpose %></td>
        <td><%= ticket.date_needed_by %></td>
        <td><%= ticket.priority %></td>
        <td><%= ticket.type_of_request %></td>
        <td><%= ticket.campus %></td>
          <% if User.find_by(id: ticket[:user_id]) %>
            <td><p><%= User.find_by(id: ticket[:user_id])[:name] %></p>
              <% if ticket.status == 'Assigned' %>
                <p><%= link_to 'Complete', ticket_path(ticket, "ticket[status]" => 'Completed'), method: :put, data: {confirm: 'Sure?'} %></p>
              <% end %>
            </td>
          <% else %>
            <td><%= link_to 'Nobody', edit_ticket_path(ticket) %></td>
          <% end %>
          <td><%= ticket.status %></td>
        <td><%= link_to 'Assign', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Delete', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %>

<%= render @ticket -%>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/users/_form.html.erb
<%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>
  <% if @user.errors.any? %>
    <div class="row">
      <div class="col col-sm-2"></div>
      <div class="input-group col-sm-7">
        <div id="" class="form-group bg-warning">
          <ul>
            <dt><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</dt>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
    
    <fieldset>
      <legend>Enter user details</legend>
      <div class="field form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="input-group col-sm-7">
          <%= f.text_field :name, size: 32, class: 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :password, class: 'col-sm-2 control-label' %>
        <div class="input-group col-sm-7">
          <%= f.password_field :password, size: 32, class: 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :password_confirmation, class: 'col-sm-2 control-label' %>
        <div class="input-group col-sm-7">
          <%= f.password_field :password_confirmation, size: 32, class: 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :email, class: 'col-sm-2 control-label' %>
        <div class="input-group col-sm-7">
          <%= f.text_field :email, class: 'form-control' %>
        </div>
      </div>
      <div class="field form-group">
        <%= f.label :admin, class: 'col-sm-2 control-label' %>
        <div class="input-group col-sm-7">
          <%= f.select :admin, [false, true], class: 'form-control' %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-2"></div>
        <%= f.submit class: 'btn btn-success' %>
      </div>
    </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="col col-sm-3"><%= user.name %></td>
        <td class="col col-sm-3"><%= user.email %></td>
        <td class="col col-sm-3"><%= user.admin %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>